config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root to: "home#index"
  resources :inns, only: [:new, :create, :index, :show, :edit, :update] do 
    get 'show_reservation', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'advanced_search', on: :collection
    get 'advanced_search_results', on: :collection
    get 'reservations', on: :collection
    get 'stay_list', on: :collection
    get 'reviews_list', on: :collection
  end
  resources :rooms, only: [:new, :create, :index, :show, :edit, :update, :destroy]  do
    get 'pre_reservation', on: :member
    resources :reservations, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update]
      get 'check', on: :collection
      get 'stay', on: :member
      get 'confirm', on: :collection
      post 'validates', on: :collection
      post 'cancel_reservation', on: :member
      post 'cancel_reservation_by_owner', on: :member
      post 'check_out', on: :member
      post 'check_in', on: :member                              
      
    end
   
  end
  
  resources :prices, only: [:new, :create, :show, :edit, :update, :destroy] 
  get 'list', to: 'reservations#list'
  namespace :api do
    namespace :v1 do
      get 'cities', to: 'inns#cities'
      get 'inns_by_city', to: 'inns#inns_by_city'
      resources :inns, only: [:index] do
        get 'rooms', on: :collection
        get 'inn_details', on: :collection
        get 'room', on: :collection
       
      end
    end
  end
  get 'cities', to: 'reservations#list'
end

app/models/inn.rb
class Inn < ApplicationRecord
  belongs_to :owner
  has_many :rooms, dependent: :destroy
  has_one :payment_method
  has_many :reservations, through: :rooms
  has_many :reviews, through: :reservations
  accepts_nested_attributes_for :payment_method

  enum pet: [:permitidos, :'não permitidos']
  enum status: [:ativa, :desativada]
  
  validates :trade_name, :company_name, :registration_number, :phone, :email, :address, :neighborhood, 
            :city, :zip_code, :description,  :payment_methods,:pet, :rules, :check_in, :check_out, :status,  presence: true
  validates :registration_number, uniqueness: true

  validates :owner_id, uniqueness: { message: "Você só pode ter uma pousada cadastrada." }

end

app/controllers/api/v1/inns_controller.rb
class Api::V1::InnsController < Api::V1::ApiController
    
    def index
        query = params['query']
        inns = Inn.where("status = 0 AND (trade_name LIKE ? OR neighborhood LIKE ? OR city LIKE ?) ", "%#{params['query']}%", "%#{params['query']}%", "%#{params['query']}%").order(:trade_name)
        render status: 200, json: inns.as_json(except: [:created_at, :updated_at])
    end

    def rooms
      
        inn = Inn.find(params[:id])
        inn.rooms
        render status: 200, json: inn.rooms.as_json(except: [:created_at, :updated_at]) 

    end

    def inn_details
        inn = Inn.find(params[:id])
        @reviews_rating = 'Sem avaliações.'
        @reviews = inn.reviews
        if @reviews.any?
            @reviews_rating = 0
            @reviews.each do |review|
                review.rating
                @reviews_rating += review.rating
            end
            @reviews_rating = @reviews_rating / @reviews.length
        end
        
        render status: 200, json: inn.as_json(except: [:created_at, :updated_at]).merge(nota: @reviews_rating)

    end


    def room
        room = Room.find(params[:id])
        reservation = Reservation.new
        reservation.start_date = params[:start]
        reservation.final_date = params[:end]
        reservation.guest_number =params[:guests]
        reservation.room_id = room.id
        if reservation.valid?
            reservation.total_price = reservation.check_value(room)
            return render status: 200, json: reservation.as_json(only: [:total_price])
        else
            render status: 422, json: { error: "Reverva não pode ser feita nessa dia ou número de hóspedes é maior que o quarto comporta." }
        end
    end

    def cities
        all_active_inns = Inn.ativa.order(:city)
        cities = all_active_inns.uniq {|item| item.city}
        return render status: 200, json: cities.as_json(only: [:city])
    end

    def inns_by_city
        all_active_inns = Inn.ativa.where("LOWER(city) LIKE ?", "%#{params[:city].downcase}%")
        return render status: 200, json: all_active_inns.as_json(except: [:created_at, :updated_at])
    end
end

app/controllers/inns_controller.rb
class InnsController < ApplicationController
    before_action :authenticate_owner!, only: [:edit]
    before_action :set_inn, only: [:show, :edit, :update, :create_payment_methods] 
    before_action :cant_edit, only: [:edit, :update, :destroy]

 
    def new
        @inn = Inn.new
    end

    def index
        @inn = Inn.find_by(owner_id: current_owner.id) 
    end

    def show
        @reviews = Review.joins(reservation: { room: :inn }).where(inns: { id: @inn.id })
        @reviews_rating = 'Sem avaliações.'

        if @reviews.any?
            @reviews_rating = 0
            @reviews.each do |review|
                review.rating
                @reviews_rating += review.rating
            end
            @reviews_rating = @reviews_rating / @reviews.length
        end
    end

    def edit
    end

    def create  
        @inn = Inn.new(inn_params)
        @inn.owner_id = current_owner.id

        if @inn.save()
            redirect_to root_path, notice: "Pousada cadastrada com sucesso."
        else
            flash.now[:notice] = "Pousada não cadastrada."
            render :new, status: 422
        end
    end
    def update
      
        if @inn.update(inn_params)
           redirect_to inn_path(@inn), notice: 'Pousada alterada com sucesso.'
        else  
            flash.now[:notice] = "Pousada não alterada."
            render :new, status: 422
        end
     end

    def cities
        @active_inns_by_city = Inn.where(status: "ativa", city: params[:city])
        names = []
        @active_inns_by_city.each do |name| 
            names << name.trade_name
        end
        @active_inns_by_city = @active_inns_by_city.order(:trade_name)
    end

    def search
        @query = params['query']
        @inns = Inn.where("trade_name LIKE ? OR neighborhood LIKE ? OR city LIKE ? ", "%#{@query}%", "%#{@query}%", "%#{@query}%")
    end

    def advanced_search
        @inns = Inn.all
    end

    def advanced_search_results
        @inns = Inn.joins(:rooms).where("pet = ? AND (trade_name LIKE ? OR neighborhood LIKE ? OR city LIKE ?) AND rooms.tv = ? AND rooms.accessible = ? AND rooms.air_conditioner = ?", params['pet'], "%#{params['query']}%", "%#{params['query']}%", "%#{params['query']}%", params['tv'], params['accessible'], params['air_conditioner'])
    end

    def reservations
        @inn = Inn.find_by(owner_id: current_owner)
        @rooms = @inn.rooms
        
    end

    def stay_list
        @inn = Inn.find_by(owner_id: current_owner)
        @rooms = @inn.rooms
        
    end


    def reviews_list
        @inn = Inn.find_by(owner_id: current_owner)
        @reviews = Review.joins(reservation: { room: :inn }).where(inns: { id: @inn.id })
    end

    private

    def inn_params
        inn_params = params.require(:inn).permit(:trade_name, :company_name, :registration_number, :phone, :email, :address, :neighborhood, :city, :zip_code, :description, :pet, :rules, :check_in, :check_out, :status, :payment_methods)
    end

    def set_inn
        @inn = Inn.find(params[:id])
    end

    def cant_edit

        redirect_to root_path unless @inn.owner_id == current_owner.id
    end

end

app/views/inns/_form.html.erb
<%= form_with(model: @inn) do |f| %>
  <div>
    <%= f.label :trade_name %>
    <%= f.text_field :trade_name %>
  </div>
  <div>
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>
  <div>
    <%= f.label :registration_number%>
    <%= f.text_field :registration_number %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <div>
    <%= f.label :email%>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :address%>
    <%= f.text_field :address %>
  </div>
  <div>
    <%= f.label :neighborhood %>
    <%= f.text_field :neighborhood %>
  </div>
  <div>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :payment_methods %>
    <%= f.text_field :payment_methods %>
  </div>
  <div>
    <%= f.label :pet %>
    <%= f.select :pet, options_for_select(Inn.pets.map {|key, value| [key.titleize, Inn.pets.key(value)]}, @inn.pet) %>
  </div>
  <div>
    <%= f.label :rules %>
    <%= f.text_field :rules %>
  </div>
  <div>
    <%= f.label :check_in %>
    <%= f.text_field :check_in %>
  </div>
  <div>
    <%= f.label :check_out %>
    <%= f.text_field :check_out %>
  </div>
  <div>
    <%= f.label :status %>
    <%= f.select :status, options_for_select(Inn.statuses.map {|key, value| [key.titleize, Inn.statuses.key(value)]}, @inn.status) %>
  </div>
  <div>
    <%= f.submit 'Salvar' %>
  </div>
<% end %>

app/views/inns/advanced_search.html.erb
<h1>Busca avançada</h1>
<div id='advanced_search'>
  <%= form_with url: advanced_search_results_inns_path, method: :get do |f| %>
    <div>
      <%=f.label :query, 'Buscar avançadamente:'%>
      <%=f.text_field :query %>
    </div>
    <div>
      <%= f.label :pet, 'Animais' %>
      <%= f.select :pet, options_for_select(Inn.pets.keys.map { |pet| [pet.titleize, Inn.pets[pet]] }) %>
    </div>
    <div>
      <%= f.label :tv, 'Tv' %>
      <%= f.select :tv, options_for_select(Room.tvs.keys.map { |tv| [tv.titleize, Room.tvs[tv]] }) %>
    </div>
    <div>
      <%= f.label :accessible, 'Acessibilidade' %>
      <%= f.select :accessible, options_for_select(Room.accessibles.keys.map { |accessible| [accessible.titleize, Room.accessibles[accessible]] }) %>
    </div>
    <div>
      <%= f.label :air_conditioner, 'Ar condicionado' %>
      <%= f.select :air_conditioner, options_for_select(Room.air_conditioners.keys.map { |air_conditioner| [air_conditioner.titleize, Room.air_conditioners[air_conditioner]] }) %>
    </div>
    <%=f.submit 'Busca avançada'%>
  <% end %>
</div>

app/views/inns/advanced_search_results.html.erb
<% if @inns.nil? %>
  <p>Não existe Pousada cadastrada.</p>
<% else %>
  <h1>
    <p><%= @inns.count %> <%= Inn.model_name.human(count: @inns.count) %> <%=I18n.translate(:found, count: @inns.count)%>.</p>
  </h1>
  <div>
    <dl>
      <%@inns.each do |inn|%>
        <dt><%= Inn.human_attribute_name(:trade_name)%>:</dt>
        <dd><%= link_to inn.trade_name, inn %></dd>
      <% end %>
    </dl>
  </div>
<% end %>

app/views/inns/cities.html.erb
<h1>Pousadas em <%=params[:city] %></h1>
<div>
  <%@active_inns_by_city.each do |inn|%>
    <dl>
      <dt>Nome: </dt>
      <%= link_to(inn) do %>
        <dd><%= inn.trade_name%></dd>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/inns/edit.html.erb
<h1>Editar dados da Pousada</h1>
<% if(@inn.errors.any?)%>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @inn.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= @inn.trade_name %>
<%= render 'form'%>

app/views/inns/index.html.erb
<h2>Sua Pousada</h2>
<% if @inn.nil? %>
  <p>Não existe Pousada cadastrada.</p>
<% else %>
  <%= @inn.trade_name %>
  <section id="inn">
    <div>
      <dl>
        <dt>Nome Fantasia:</dt>
        <dd><%= @inn.trade_name %></dd>
        <dt>Razão Social:</dt>
        <dd><%= @inn.company_name %></dd>
        <dt>CNPJ:</dt>
        <dd><%= @inn.registration_number %></dd>
        <dt>Telefone:</dt>
        <dd><%= @inn.phone %></dd>
        <dt>Email:</dt>
        <dd><%= @inn.email %></dd>
      </dl>
    </div>
    <%= link_to 'Detalhes', inn_path(@inn)%>
  <% end%>
</section>

app/views/inns/new.html.erb
<h1>Cadastre sua pousada</h1>
<% if(@inn.errors.any?)%>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @inn.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= render 'form'%>

app/views/inns/reservations.html.erb
<h1>Todas as reservas</h1>
<% @rooms.each do |room|%>
  <dl>
    <% room.reservations.where(status: :active).each do |reservation|%>
      <dt>Nome do quarto:</dt>
      <dd><%= link_to reservation.room.name, room_reservation_path(reservation.room, reservation) %></dd>
      <dt>Check in:</dt>
      <dd><%= I18n.l(reservation.start_date.to_date)%></dd>
      <dt>Check out:</dt>
      <dd><%= I18n.l(reservation.final_date.to_date)%></dd>
      <dt>Código da reserva:</dt>
      <dd><%= reservation.code%></dd>
      <dt>Quantidade de hóspedes:</dt>
      <dd><%= reservation.guest_number%></dd>
      <p>-----------------------------------------</p>
    <%end%>
  <% end %>
</dl>

app/views/inns/reviews_list.html.erb
<h1>Avaliações das Estadias:</h1>
<div>
  <dl>
    <% if @reviews.nil?%>
      <h2>Sem avaliações no momento.</h2>
    <% else %>
      <% @reviews.each do |review| %>
        <dt>Nome do quarto:</dt>
        <dd><%= review.reservation.room.name%></dd>
        <dt>Nota:</dt>
        <dd><%= review.rating%></dd>
        <dt>Comentário:</dt>
        <dd><%= review.comment%></dd>
        <dt>Nome do hóspede:</dt>
        <dd><%= Guest.find(review.reservation.guest_id).name%></dd>
        <%= link_to 'Responder', edit_room_reservation_review_path(review.reservation.room, review.reservation, review) %>
      <% end %>
    <% end %>
  </dl>
</div>

app/views/inns/search.html.erb
<% if @inns.nil? %>
  <p>Não existe Pousada cadastrada.</p>
<% else %>
  <h1>
    <p><%= @inns.count %> <%= Inn.model_name.human(count: @inns.count) %> <%=I18n.translate(:found, count: @inns.count)%>.</p>
  </h1>
  <div>
    <dl>
      <%@inns.each do |inn|%>
        <dt><%= Inn.human_attribute_name(:trade_name)%>:</dt>
        <dd><%= link_to inn.trade_name, inn %></dd>
      <% end %>
    </dl>
  </div>
<% end %>
<%= link_to 'Busca avançada', advanced_search_inns_path %>

app/views/inns/show.html.erb
<h2>Detalhes da Pousada</h2>
<% if @inn.nil? %>
  <p>Não existe Pousada cadastrada.</p>
<% else %>
  <%= @inn.trade_name %>
  Nota: <%= @reviews_rating %>
  <section id="inn">
    <div>
      <dl>
        <dt><%= Inn.human_attribute_name(:trade_name)%>:</dt>
        <dd><%= @inn.trade_name %></dd>
        <% if (current_owner.present? && current_owner.owner?) %>
          <dt><%= Inn.human_attribute_name(:company_name)%>:</dt>
          <dd><%= @inn.company_name %></dd>
          <dt>CNPJ:</dt>
          <dd><%= @inn.registration_number %></dd>
        <% end %>
        <dt><%= Inn.human_attribute_name(:email)%>:</dt>
        <dd><%= @inn.email %></dd>
        <dt><%= Inn.human_attribute_name(:address)%>:</dt>
        <dd><%= @inn.address %></dd>
        <dt><%= Inn.human_attribute_name(:neighborhood)%>:</dt>
        <dd><%= @inn.neighborhood %></dd>
        <dt><%= Inn.human_attribute_name(:city)%>:</dt>
        <dd><%= @inn.city %></dd>
        <dt><%= Inn.human_attribute_name(:phone)%>:</dt>
        <dd><%= @inn.phone %></dd>
        <dt><%= Inn.human_attribute_name(:zip_code)%>:</dt>
        <dd><%= @inn.zip_code %></dd>
        <dt><%= Inn.human_attribute_name(:description)%>:</dt>
        <dd><%= @inn.description %></dd>
        <dt><%= Inn.human_attribute_name(:payment_methods)%>:</dt>
        <dd><%= @inn.payment_methods %></dd>
        <dt><%= Inn.human_attribute_name(:pet)%>:</dt>
        <dd><%= @inn.pet %></dd>
        <dt><%= Inn.human_attribute_name(:rules)%>:</dt>
        <dd><%= @inn.rules %></dd>
        <dt><%= Inn.human_attribute_name(:check_in)%>:</dt>
        <dd><%= @inn.check_in.strftime('%H:%M') %></dd>
        <dt><%= Inn.human_attribute_name(:check_out)%>:</dt>
        <dd><%= @inn.check_out.strftime('%H:%M') %></dd>
        <dt><%= Inn.human_attribute_name(:status)%>:</dt>
        <dd><%= @inn.status %></dd>
      </dl>
    </div>
    <% if (current_owner.present? ) %>
      <%= link_to 'Editar detalhes', edit_inn_path(@inn)%>
      <% rooms = @inn.rooms%>
    <% else %>
      <% rooms = @inn.rooms.where(available: :sim)%>
    <% end %>
    <p>---------------------------------------</p>
    <h2>Quartos disponíveis</h2>
    <% rooms.each do |room| %>
      <dl>
        <dt>Nome:</dt>
        <dd> <%= link_to "#{room.name}", room_path(room)%></dd>
        <dt>Descrição:</dt>
        <dd><%= room.description %></dd>
        <dt>Tamanho:</dt>
        <dd><%= room.size %></dd>
        <dt>Hóspedes:</dt>
        <dd><%= room.guest %></dd>
        <dt>Diária:</dt>
        <%= number_to_currency(current_price(room), locale: :'pt-BR') %>
        <dt>Varanda: </dt>
        <dd><%= room.balcony %></dd>
        <dt>Tv:</dt>
        <dd><%= room.tv %></dd>
        <dt>Guarda-roupas:</dt>
        <dd><%= room.wardrobe %></dd>
        <dt>Cofre:</dt>
        <dd><%= room.safe %></dd>
        <dt>Acessibilidade:</dt>
        <dd><%= room.accessible %></dd>
        <dt>Ar condicionado: </dt>
        <dd><%= room.air_conditioner %></dd>
        <dt>Disponibilidade:</dt>
        <dd><%= room.available %></dd>
      </dl>
    <% end%>
  <% end%>
</section>

app/views/inns/stay_list.html.erb
<h1>Todas as reservas</h1>
<% @rooms.each do |room|%>
  <dl>
    <% room.reservations.where(status: :'active stay').each do |reservation|%>
      <dt>Nome do quarto:</dt>
      <dd><%= link_to reservation.room.name, stay_room_reservation_path(reservation.room, reservation) %></dd>
      <dt>Check in:</dt>
      <dd><%= I18n.l(reservation.start_date.to_date)%></dd>
      <dt>Check out:</dt>
      <dd><%= I18n.l(reservation.final_date.to_date)%></dd>
      <dt>Código da reserva:</dt>
      <dd><%= reservation.code%></dd>
      <dt>Quantidade de hóspedes:</dt>
      <dd><%= reservation.guest_number%></dd>
      <p>-----------------------------------------</p>
    <%end%>
  <% end %>
</dl>