config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root to: "home#index"
  resources :inns, only: [:new, :create, :index, :show, :edit, :update] do 
    get 'show_reservation', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'advanced_search', on: :collection
    get 'advanced_search_results', on: :collection
    get 'reservations', on: :collection
    get 'stay_list', on: :collection
    get 'reviews_list', on: :collection
  end
  resources :rooms, only: [:new, :create, :index, :show, :edit, :update, :destroy]  do
    get 'pre_reservation', on: :member
    resources :reservations, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update]
      get 'check', on: :collection
      get 'stay', on: :member
      get 'confirm', on: :collection
      post 'validates', on: :collection
      post 'cancel_reservation', on: :member
      post 'cancel_reservation_by_owner', on: :member
      post 'check_out', on: :member
      post 'check_in', on: :member                              
      
    end
   
  end
  
  resources :prices, only: [:new, :create, :show, :edit, :update, :destroy] 
  get 'list', to: 'reservations#list'
  namespace :api do
    namespace :v1 do
      get 'cities', to: 'inns#cities'
      get 'inns_by_city', to: 'inns#inns_by_city'
      resources :inns, only: [:index] do
        get 'rooms', on: :collection
        get 'inn_details', on: :collection
        get 'room', on: :collection
       
      end
    end
  end
  get 'cities', to: 'reservations#list'
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  has_one :review
  validates :guest_number, presence: true
  validates :start_date, presence: true
  validates :final_date, presence: true
  validates :guest_number, :final_date, :start_date, presence: true
  validate :number_of_guests, :validate_past_date, :validade_final_date, :validate_dates
  validates :code, presence: true
  validates :code, uniqueness: true
  before_validation :generate_code, on: :create
  enum status: {  canceled: 0, active: 1, 'active stay': 3, ended: 4   }
 

  def number_of_guests
    room = Room.find(self.room_id)
    if self.guest_number > room.guest.to_i
      return errors.add(:guest_number, "Número de hóspede é maior do que o quarto suporta.")
    end

  end
  def validate_past_date
    if self.start_date < Date.today 
      return errors.add(:start_date, "Não pode fazer reserva para datas anteriores ao dia atual.")
    end
  end

  def validade_final_date
    if self.start_date > self.final_date 
      return errors.add(:start_date, "Não pode fazer reserva com data de saída anterior da data de entrada.")
    end
  end

  def validate_dates  
    
    current_range = (self.start_date..self.final_date)
    ranges = Reservation.where(room_id: self.room_id, status: :active)
    ranges.each do |range|
     new_range = range.start_date..range.final_date
      if (current_range.overlaps?new_range) && (self.id != range.id)
        return errors.add(:start_date, " - Essa data já está em uso.")
      end
    end
  end

  def check_value(room)
    range = self.start_date..self.final_date
    total_price = 0
    season_days = 0
    range.each do |day|
        room.prices.each do |price|
            if day.between?(price.start_date, price.final_date) == true
                total_price = total_price + price.new_rate
                season_days += 1
            end
        end
    end
    
    total_regular_price = range.count - season_days
    total_price = total_price + (total_regular_price * room.daily_rate)
    
  end

  def generate_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    before_action :authenticate_guest!, only: [:new]
    before_action :authenticate_guest_or_owner!, only: [:show]
    before_action :set_room, only: [:new, :show, :check, :confirm, :validates, :create, :cancel_reservation, :check_in, :stay, :cancel_reservation_by_owner, :check_out]
    before_action :set_inn, only: [:new, :show, :create, :cancel_reservation, :check_in, :stay, :cancel_reservation_by_owner, :check_out]
    before_action :set_reservation, only: [:show, :cancel_reservation, :check_in, :stay, :cancel_reservation_by_owner, :check_out]
    

    def index
        @reservations = Reservation.where(guest_id: current_guest.id)
    end
    def new
        @reservation = Reservation.new
        @reservation.total_price = session[:price]
        @reservation.guest_number = session[:guest]
        @reservation.start_date = session[:start]
        @reservation.final_date = session[:final]
       
        range = @reservation.start_date..@reservation.final_date
    end

    def show
        if @reservation.review 
            @review = @reservation.review
        end
       
    end
    
    def list
        @reservations = Reservation.where(guest_id: current_guest.id, status: [:active, :ended])
    end

    def check
        @reservation = Reservation.new
    end

    def create
        @prices = Price.where(room_id: @room.id)
        @reservation = Reservation.new(set_params)
        @reservation.guest_id = current_guest.id
        @reservation.room_id = @room.id
        @reservation.status = 1

        
        if @reservation.save()
            redirect_to list_path, notice: 'Reserva confirmada com sucesso.'
        else  
            flash.now[:notice] = "Reserva não foi confirmada, tente novamente."
            render :new, status: 422
        end
    end

    def confirm
        @reservation = Reservation.new
    end
    
    def validates
        if params[:reservation].nil? || params[:reservation][:guest_number].blank? || params[:reservation][:start_date].blank? || params[:reservation][:final_date].blank?
            return redirect_to check_room_reservations_path(@room), notice: 'Campos não podem estar vazios.'      
        end
        @reservation = Reservation.new
        session[:has_pre_reservation] = true
        @reservation.room_id = session[:room] = @room.id
        @reservation.start_date = session[:start] = params[:reservation][:start_date]
        @reservation.final_date = session[:final] = params[:reservation][:final_date]
        @reservation.guest_number = session[:guest] = params[:reservation][:guest_number].to_i
        if @reservation.valid?
            current_range = @reservation.start_date..@reservation.final_date 
            @reservation.total_price = session[:price] = check_value(current_range)
            flash.now[:notice] = "Pre-reserva feita com sucesso."    
            return  render 'reservations/confirm', status: 422

        else
            flash.now[:notice] = "Pre-reserva não pode ser feita, data já foi reservada ou número hóspedes é maior do que a o quarto suporta."    
            return render :check, status: 422
        end 
    end
   
    def cancel_reservation
        if @reservation.start_date < 7.day.from_now 
            flash.now[:notice] = "A reserva não pode ser cancelada com menos de 7 dias para o check in."    
            return render :show, status: 422 
        else
           @reservation.update(status: :canceled)
            redirect_to room_reservation_path(@room, @reservation), notice: 'Reserva cancelada com sucesso.'
        end
       
    end

    def cancel_reservation_by_owner
        if @reservation.start_date.to_date <= Date.today - 2 
            @reservation.update_column(:status, :canceled)
            redirect_to room_reservation_path(@room, @reservation), notice: 'Reserva cancelada com sucesso.'
        else
            flash.now[:notice] = "A reserva não pode ser cancelada antes do segundo dia do Check in"    
            return render :show, status: 422 
        end
    end

    def check_in
        if @reservation.start_date >= Date.today
            @reservation.update!(status: :'active stay', check_in_date: Date.today, check_in_time: Time.zone.now)
            return redirect_to stay_room_reservation_path(@room, @reservation), notice: "Check in do hóspede feito com sucesso"
        else
            flash.now[:notice] = "O check in não pode ser feito antes do dia de entrada da reserva."    
            return render :show, status: 422 
        end
    end

    def check_out
            if Time.zone.now.strftime('%H:%M') > @inn.check_out.strftime('%H:%M')
                new_price = check_value(@reservation.check_in_date..1.day.from_now)  
            else
                new_price = check_value(@reservation.check_in_date..Date.today)
            end 

            @reservation.update!(status: :'ended', check_out_date: Date.today, check_out_time: Time.zone.now, total_price: new_price, payment: params["payment"])
            return redirect_to stay_room_reservation_path(@room, @reservation), notice: "Check out do hóspede feito com sucesso"
    end

    def stay

    end

    private
   

    def set_reservation
        @reservation = Reservation.find(params[:id])
    end

    def set_room
        @room = Room.find(params[:room_id])
    end

    def set_inn
        @inn = Inn.find_by(id: @room.inn_id)
    end
   
    def check_value(range)
        total_price = 0
        season_days = 0
        range.each do |day|
            @room.prices.each do |price|
                if day.between?(price.start_date, price.final_date) == true
                    total_price += price.new_rate
                    season_days += 1
                end
            end
        end
        
        total_regular_price = range.count - season_days
        total_price = total_price + (total_regular_price * @room.daily_rate)
        @total_price = total_price
    end

    def set_params
        reservation_params = params.require(:reservation).permit(:guest_number, :start_date, :final_date, :total_price, :room_id, :guest_id)
    end

    def authenticate_guest_or_owner!
        unless owner_signed_in? || guest_signed_in?
            redirect_to root_path, alert: 'Você precisa estar logado para ter acesso a essa informação.'
        end
    end
end

app/views/reservations/_details.html.erb
<dt>Nome do quarto:</dt>
<dd><%= @room.name %></dd>
<dt>Código da reserva:</dt>
<dd><%= @reservation.code %></dd>
<dt>Status da reserva:</dt>
<dd><%= I18n.t(@reservation.status) %></dd>
<dt>Número de hóspedes:</dt>
<dd><%= @reservation.guest_number %></dd>
<dt>Preço total da estadia:</dt>
<dd><%= number_to_currency(@reservation.total_price, locale: :'pt-BR') %></dd>
<dt>Check in:</dt>
<dd><%= I18n.l(@reservation.start_date.to_date) %></dd>
<dt>Check out:</dt>
<dd><%= I18n.l(@reservation.final_date.to_date) %></dd>
<dd><%= @inn.payment_methods %></dd>
<dt>Horário de check in:</dt>
<dd><%= @inn.check_in.strftime('%H:%M')  %></dd>
<dt>Horário de check out:</dt>
<dd><%= @inn.check_out.strftime('%H:%M') %></dd>

app/views/reservations/check.html.erb
<h1>Quando deseja se hospedar?</h1>
Nome: <%= @room.name%>
<% if(@reservation.errors.any?)%>
  <p>Verifique os erros abaixo:</p>
  <ul>
    <% @reservation.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @reservation, url: validates_room_reservations_path, method: :post) do |f| %>
  <div class="field">
    <%= f.label :guest_number %>
    <%= f.text_field :guest_number %>
  </div>
  <div>
    <%= f.label :start_date %>
    <%= f.date_field :start_date%>
  </div>
  <div>
    <%= f.label :final_date%>
    <%= f.date_field :final_date%>
  </div>
  <div class="actions">
    <%= f.submit "Fazer pre-reserva" %>
  </div>
<% end %>

app/views/reservations/confirm.html.erb
<h1>Detalhes da Reserva</h1>
<div>
  <dl>
    <dt>Nome:</dt>
    <dd><%= @room.name %></dd>
    <dt>Preço da reserva:</dt>
    <dd><%= number_to_currency(@reservation.total_price, locale: :'pt-BR') %></dd>
    <dt>Hóspedes:</dt>
    <dd><%= @reservation.guest_number%></dd>
    <dt>Check-in:</dt>
    <dd><%= I18n.l(session[:start].to_date) %></dd>
    <dt>Check-out:</dt>
    <dd><%= I18n.l(session[:final].to_date)%></dd>
  </dl>
  <%= link_to 'Fazer Reserva', new_room_reservation_path(price: @reservation.total_price, room_id: @room.id, guest_number: @reservation.guest_number, start: @reservation.start_date, end: @reservation.final_date) %>

app/views/reservations/list.html.erb
<h1>Minhas reservas</h1>
<div>
  <% if @reservations.nil? %>
    <h3>Você não tem reservas feita.</h3>
  <% else %>
    <dl>
      <% @reservations.each do |reservation| %>
        <dt>Nome do quarto:</dt>
        <dd> <%= link_to reservation.room.name,  room_reservation_path(reservation.room, reservation)%></dd>
        <dt>Código da reserva:</dt>
        <dd><%= reservation.code %></dd>
        <dt>Status da reserva:</dt>
        <dd><%= I18n.t(reservation.status) %></dd>
        <dt>Número de hóspedes:</dt>
        <dd><%= reservation.guest_number %></dd>
        <dt>Preço total da estadia:</dt>
        <dd><%= number_to_currency(reservation.total_price, locale: :'pt-BR') %></dd>
        <dt>Dia da entranda:</dt>
        <dd><%= I18n.l(reservation.start_date.to_date) %></dd>
        <dt>Dia da saída:</dt>
        <dd><%= I18n.l(reservation.final_date.to_date) %></dd>
        <dd><%= reservation.room.inn.payment_methods %></dd>
        <dt>Check in:</dt>
        <dd><%= reservation.room.inn.check_in.strftime('%H:%M') %></dd>
        <dt>Check out:</dt>
        <dd><%= reservation.room.inn.check_out.strftime('%H:%M') %></dd>
        <dt>Endereço:</dt>
        <%= reservation.room.inn.address %>
        <dt>Endereço:</dt>
        <%= reservation.room.inn.city %>
        <p> ------------------------------ </p>
      <% end %>
    </dl>
  <% end %>
</div>

app/views/reservations/new.html.erb
<h1>Confirmar sua reserva:</h1>
<div>
  <dl>
    <dt>Nome:</dt>
    <dd><%= @room.name %></dd>
    <dt>Número de hóspedes:</dt>
    <dd><%= session[:guest] %></dd>
    <dt>Preço total da estadia:</dt>
    <dd><%= number_to_currency(session[:price], locale: :'pt-BR') %></dd>
    <dt>Dia da entranda:</dt>
    <dd><%= I18n.l(session[:start].to_date) %></dd>
    <dt>Dia da saída:</dt>
    <dd><%= I18n.l(session[:final].to_date) %></dd>
    <dt>Métodos de Pagamento:</dt>
    <dd><%= @inn.payment_methods %></dd>
    <dt>Check in:</dt>
    <dd><%= @inn.check_in.strftime('%H:%M') %></dd>
    <dt>Check out:</dt>
    <dd><%= @inn.check_out.strftime('%H:%M') %></dd>
  </dl>
</div>
<%= form_with(model: [@room, @reservation]) do |f| %>
  <div class="field">
    <%= f.hidden_field :guest_number %>
  </div>
  <div>
    <%= f.hidden_field  :total_price%>
  </div>
  <div>
    <%= f.hidden_field  :start_date%>
  </div>
  <div>
    <%= f.hidden_field  :final_date%>
  </div>
  <div class="actions">
    <%= f.submit "Confirmar Reserva" %>
  </div>
<% end %>

app/views/reservations/show.html.erb
<h1>Detalhes da Reserva</h1>
<div>
  <dl>
    <%= render 'details' %>
  </dl>
</div>
<% if owner_signed_in? %>
  <% if @reservation.active? %>
    <%= button_to "Check in", check_in_room_reservation_path(@room, @reservation), method: :post%>
    <%= button_to "Cancelar reserva", cancel_reservation_by_owner_room_reservation_path(@room, @reservation), method: :post%>
  <% end %>
<% elsif guest_signed_in? %>
  <% if @reservation.ended? %>
    <% if @reservation.review.nil? %>
      <%= link_to "Avaliar estadia", new_room_reservation_review_path(@room, @reservation)%>
    <% else%>
      <%= link_to "Ver avaliação", room_reservation_review_path(@room, @reservation, @review)%>
    <% end %>
  <% end %>
  <%= button_to "Cancelar Reserva", cancel_reservation_room_reservation_path(@room, @reservation), method: :post%>
<% end %>

app/views/reservations/stay.html.erb
<h1>Detalhes da estadia</h1>
<div>
  <dl>
    <%= render 'details' %>
    <dt>Dia real do check in:</dt>
    <dd><%=  I18n.l(@reservation.check_in_date.to_date) %></dd>
    <dt>Hora real do check in:</dt>
    <dd><%= @reservation.check_in_time.strftime('%H:%M') %></dd>
    <% if @reservation.ended? %>
      <dt>Dia real do check out:</dt>
      <dd><%=  I18n.l(@reservation.check_out_date.to_date) %></dd>
      <dt>Hora real do check out:</dt>
      <dd><%= @reservation.check_out_time.strftime('%H:%M') %></dd>
      <dt>Método de pagamento usado:</dt>
      <dd><%= @reservation.payment %></dd>
    <%end%>
  </dl>
  <% if @reservation.active_stay? %>
    <%= form_tag(check_out_room_reservation_path, method: :post) do %>
      <%= text_field_tag(:payment, nil, placeholder: 'Forma de pagamento escolhida') %>
      <%= submit_tag('Check out') %>
    <% end %>
  <% end %>
</div>