config/routes.rb
Rails.application.routes.draw do
  devise_for :guests
  devise_for :owners
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
  root to: "home#index"
  resources :inns, only: [:new, :create, :index, :show, :edit, :update] do 
    get 'show_reservation', on: :member
    get 'cities', on: :collection
    get 'search', on: :collection
    get 'advanced_search', on: :collection
    get 'advanced_search_results', on: :collection
    get 'reservations', on: :collection
    get 'stay_list', on: :collection
    get 'reviews_list', on: :collection
  end
  resources :rooms, only: [:new, :create, :index, :show, :edit, :update, :destroy]  do
    get 'pre_reservation', on: :member
    resources :reservations, only: [:new, :create, :show] do
      resources :reviews, only: [:new, :create, :show, :edit, :update]
      get 'check', on: :collection
      get 'stay', on: :member
      get 'confirm', on: :collection
      post 'validates', on: :collection
      post 'cancel_reservation', on: :member
      post 'cancel_reservation_by_owner', on: :member
      post 'check_out', on: :member
      post 'check_in', on: :member                              
      
    end
   
  end
  
  resources :prices, only: [:new, :create, :show, :edit, :update, :destroy] 
  get 'list', to: 'reservations#list'
  namespace :api do
    namespace :v1 do
      get 'cities', to: 'inns#cities'
      get 'inns_by_city', to: 'inns#inns_by_city'
      resources :inns, only: [:index] do
        get 'rooms', on: :collection
        get 'inn_details', on: :collection
        get 'room', on: :collection
       
      end
    end
  end
  get 'cities', to: 'reservations#list'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pousadaria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="bg-light">
    <div class="container">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Pousadaria</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <%= link_to "Início", root_path, class:'nav-link' %>
              </li>
              <% if owner_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Reservas', reservations_inns_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Estadias ativas', stay_list_inns_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Avaliações', reviews_list_inns_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Cadastrar pousada', new_inn_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Pousada', inns_path,class:'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Quartos', rooms_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to 'Perfil', edit_owner_registration_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                  Olá <%= current_owner.name%>
                  <%= current_owner.email%>
                </li>
                <li class="nav-item">
                  <%= button_to 'Sair', destroy_owner_session_path, method: :delete, class:'btn btn-outline-danger mx-3' %>
                </li>
              <% elsif guest_signed_in? %>
                <li class="nav-item">
                  <%= link_to "Perfil", edit_guest_registration_path , class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to "Minhas reservas", list_path , class:'nav-link'%>
                </li>
                <li class="nav-item">
                  Olá <%= current_guest.name%>
                </li>
                <li class="nav-item">
                  <%= button_to 'Sair', destroy_guest_session_path, method: :delete, class:'btn btn-outline-danger mx-3' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "Anfitrião", new_owner_session_path , class:'nav-link'%>
                </li>
                <li class="nav-item">
                  <%= link_to "Hóspede", new_guest_session_path , class:'nav-link'%>
                </li>
              <% end %>
            </ul>
            <%= form_with url: search_inns_path, class:"d-flex", method: :get do |f| %>
              <%=f.label :query, 'Buscar pousada:'%>
              <%=f.text_field :query, class:'form-control me-2'%>
              <%=f.submit 'Buscar', class: 'btn-outline-success'%>
            <% end %>
          </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <main>
        <%= yield %>
      </main>
    </div>
    <footer class="mt-5 pt-5"></footer>
  </body>
</html>